### ISSUE TITLE
Ability to make replacements with uppercase/lowercase patterns

### ISSUE THREAD

**Issue by samy** [rmariuzzo/Laravel-JS-Localization#101]
With Laravel Translator API, we have the ability to convert some replacements patterns letter to uppercase or lowercase.

For example, if you replace `:Exclude` by passing [ exclude => "exclude me" ], you will obtain "Exclude me" (first E is capitalized as in translation pattern).

It should be useful to have it in Laravel-JS-Localization 👍

**Comment by rmariuzzo** [comment]
I agree, I will keep this issue open here for visibility as we work with it into the right place: https://github.com/rmariuzzo/Lang.js

**Comment by rmariuzzo** [comment]
Created the issue here: https://github.com/rmariuzzo/Lang.js/issues/47

**Comment by rmariuzzo** [comment]
Hey @samy! I have added that feature and released at: https://github.com/rmariuzzo/Lang.js/releases/tag/v1.1.6 I will update shortly this package with latest Lang.js.

**Comment by a-komarev** [comment]
@rmariuzzo Thanks!

**Comment by samy** [comment]
Great ! Thanks for reactivity !

**Comment by rmariuzzo** [comment]
This was released.
