### ISSUE TITLE
getting 500 error

### ISSUE THREAD

**Issue by sadiss** [rmariuzzo/Laravel-JS-Localization#102]
After following the Instructions I am getting Internal server error on latest laravel 5.4

**Comment by rmariuzzo** [comment]
@sadiss is this happening in a fresh Laravel installation?

**Comment by sadiss** [comment]
I figured is out i was permission error. But i was not able to use translation method in standalone js file. can you do some kind of video tutorial on this package?

**Comment by rmariuzzo** [comment]
I could, but not immediately. How are you trying to ‘use the translation method in standalone js‘?

**Comment by sadiss** [comment]
using the Lang.get('messages.home'); in my app.js file

**Comment by rmariuzzo** [comment]
@sadiss any stack trace?

**Comment by sadiss** [comment]
@rmariuzzo No nothing no error shows up but no translation

**Comment by rmariuzzo** [comment]
I will close this one as we don't have enough information to reproduce the issue.
