### ISSUE TITLE
Can't get it to work! :(

### ISSUE THREAD

**Issue by razvaniacob** [rmariuzzo/Laravel-JS-Localization#110]
I need help! I'm generating the file via php artisan command and I include the generated js file that has all my messages and the library to my html page. I set the locals but when I try to get the message like so: Lang.get('messages.hello') it can't find the key. 

What should I do now?

**Comment by razvaniacob** [comment]
I created a js fiddle with my code

https://jsfiddle.net/c04h9sn3/

**Comment by razvaniacob** [comment]
I figure it out!... sorry for this!

**Comment by rmariuzzo** [comment]
Just noticed it 👍
