### ISSUE TITLE
output directory created without any permissions

### ISSUE THREAD

**Issue by ameenross** [rmariuzzo/Laravel-JS-Localization#111]
This oneliner can be run in artisan:

```php
$f = new Illuminate\FileSystem\FileSystem; $f->makeDirectory('zzz', null, true);
```

It will yield a directory `zzz` without any permissions. That's because makeDirectory is basically just a wrapper around PHP's mkdir. And the filemode argument passed here is null. Unfortunately Laravel doesn't do anything clever when you pass `null`, and the default mode is only set on the function definition.

This is how the LangJsGenerator also creates the output directory: `$this->file->makeDirectory($dirname, null, true);`

It can be solved by passing `0755` instead of null

**Comment by rmariuzzo** [comment]
Thank you mate!

**Comment by ameenross** [comment]
You're welcome :smile:
Thanks for the prompt response
