### ISSUE TITLE
Localized strings with a dot in their name are unrenderable

### ISSUE THREAD

**Issue by ERPedersen** [rmariuzzo/Laravel-JS-Localization#115]
**strings.php**
```php
return [
    'info' => 'More info',
    'link.info' => 'Get more info',
];
```

```javascript
Lang.get('strings.info'); // Outputs "More info"
Lang.get('strings.link.info'); // Outputs "strings.link.info"
``` 

Seems like if my strings are separated by a dot, they are unrenderable

**Comment by rmariuzzo** [comment]
This will be addressed at: https://github.com/rmariuzzo/Lang.js/issues/54

I will keep this issue open until solved at Lang.js and pulled into this repo.

**Comment by ERPedersen** [comment]
Awesome. Thanks for your feedback :)

**Comment by rmariuzzo** [comment]
@ERPedersen progress has been made. I'm waiting to support a tricky test, then it will be merged ASAP.

**Comment by ERPedersen** [comment]
Any progress on this yet?

**Comment by rmariuzzo** [comment]
Sorry for the long wait @ERPedersen and all other devs. This has been published now!

**Comment by cat-labs** [comment]
Hi Rubens,

I just noticed another small issue if you are interested in fixing it :-)

**layout.php**

`return [
    'test' => 'this is a test',
    'test.sub' => 'this is a sub test'`

`Lang.get('layout.test'); // Outputs "this is a test"
Lang.get('layout.test.sub'); // Outputs "this is a test"`

This works in Laravel
