### ISSUE TITLE
Access to empty value into Language Translation return key

### ISSUE THREAD

**Issue by Daviex** [rmariuzzo/Laravel-JS-Localization#119]
Hey.
Got this problem:
I try to get the message from locale file that has empty value, it can find it but return the key I asked for, while, If I add a space as a value, it give me the result.

I'm doing it wrong?

Thanks

**Comment by rmariuzzo** [comment]
This should be an issue of rmariuzzo/lang.js. Will check it later.

**Comment by Daviex** [comment]
Ok thank you

**Comment by rmariuzzo** [comment]
@Daviex a quick update, this has been fixed in [Lang.js](https://github.com/rmariuzzo/Lang.js). Soon, this tool will be also updated.

**Comment by rmariuzzo** [comment]
This has been fixed in the latest version ([v1.4.7](https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.4.7)).

**Comment by Daviex** [comment]
Tried, it works, thanks so much!
