### ISSUE TITLE
This is awesome! Any plans for a Laravel 5 compatible version?

### ISSUE THREAD

**Issue by rohan-deshpande** [rmariuzzo/Laravel-JS-Localization#13]
I'm building a Laravel 5 app using React JS and I would really love this to be updated, problem is I'm not too sure what is causing the conflicts, seems like the Illuminate requirements?

**Comment by rmariuzzo** [comment]
Yes, I suspect the problem is the Illuminate requirements and maybe I will need to update the lang path. I will check on this when I get some time, right now I'm pretty busy.

**Comment by rohan-deshpande** [comment]
All good, I wrote an interim solution with my own JS and a PHP file that just reads the directory and converts all the arrays to JavaScript objects and then puts then in `js/lang/en/*` works well enough for now!

**Comment by jisuo** [comment]
Hey, also interested in Laravel 5 support, any news?

**Comment by rmariuzzo** [comment]
I will start in a few minutes.

**Comment by sboo** [comment]
@rmariuzzo Check this fork from yours https://github.com/xAockd/Laravel-JS-Localization 
I made a fork from that and made it compatible. only a few changes were needed.

**Comment by rmariuzzo** [comment]
Thanks @sboo! Are you willing to make a PR so I can review + merge?

**Comment by sboo** [comment]
sure thing

**Comment by rmariuzzo** [comment]
Thanks @sboo for your support and collaboration on this. This package was updated and now it supports Laravel 5.
