### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by bjorkgard** [rmariuzzo/Laravel-JS-Localization#151]
It is possible to add support for Laravel 8?

**Comment by artsur** [comment]
Good question! I try to find solution too..

**Comment by roldandvg** [comment]
hello, is there an approximate date planned for the support update to laravel 8 ?, thanks

**Comment by rmariuzzo** [comment]
I'm gonna check that this week. Tomorrow, will invest a couple of mins to check that stack trace. Thank you all! Any extra help appreciated.

**Comment by mjducharme** [comment]
Is there something wrong with the pull request that was submitted for this?

https://github.com/rmariuzzo/Laravel-JS-Localization/pull/153

**Comment by rmariuzzo** [comment]
I see it passing, let's merge this!

**Comment by rmariuzzo** [comment]
Just code reviewed the PR and merged. Will create a new tag.

**Comment by rmariuzzo** [comment]
New tag/version created: https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.7.0 - Please test and let me know how it goes. Thanks for your efforts and patience.

**Comment by asbiin** [comment]
@rmariuzzo  I confirm it's working with Laravel 8, you can close this issue

**Comment by realtebo** [comment]
Version 1.,7.0 has still the wrong requirements in its composer.json ! 
Please update composer.json to allow ^8.0

**Comment by rmariuzzo** [comment]
I apologize for my long reply. I will take a look this week.
