### ISSUE TITLE
Request to enable support for PHP 8

### ISSUE THREAD

**Issue by realtebo** [rmariuzzo/Laravel-JS-Localization#158]
Hi !

We're using this package since v1.2

A big project is now being migrated to PHP 8 and we discovered that v1.7 has a composer.json requirements for php 7.

Could you please extends supports for php 8?

**Comment by rmariuzzo** [comment]
Yes, I can do that.

**Comment by GENL** [comment]
I suggest to use Matice: https://github.com/GENL/matice

**Comment by rmariuzzo** [comment]
> I suggest to use Matice: https://github.com/GENL/matice

Hi @GENL!

I'm happy to include a reference for Matice in the README file of this project.

**Comment by rmariuzzo** [comment]
@realtebo I'm checking this now.

**Comment by rmariuzzo** [comment]
Just merged this: #154

**Comment by rmariuzzo** [comment]
[Just published v1.8.0](https://packagist.org/packages/mariuzzo/laravel-js-localization#v1.8.0)

**Comment by realtebo** [comment]
Thank  you a lot

**Comment by rmariuzzo** [comment]
Lmk if it works for you

**Comment by realtebo** [comment]
It works fine with PHP  8 and larevel 8.x, thanks

**Comment by rmariuzzo** [comment]
Thank you for your feedback @realtebo !
