### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by HadrienX** [rmariuzzo/Laravel-JS-Localization#164]
Laravel 9 was released today.

Please update your package settings to add PHP 8 and Laravel 9 support.

Current error :

> mariuzzo/laravel-js-localization v1.7.0 requires php ^5.4 || ^7.0 -> your php version (8.0.3) does not satisfy that requirement.

**Comment by ahoiroman** [comment]
Should be solved with https://github.com/rmariuzzo/Laravel-JS-Localization/pull/162

**Comment by HadrienX** [comment]
I just found an error on Laravel 9.
The `lang` directory has moved from `/resources/lang` directory to `/lang` directory on fresh install.

In `LaravelJsLocalizationServiceProvider@register` method of this package, the lang directory is defined to :
`$app['path.base'].'/resources/lang'`
on Laravel > 5.

I guess the best way to handle Laravel 9 new language directory is to add a new config variable to define the lang directory.
