### ISSUE TITLE
Chrome issue

### ISSUE THREAD

**Issue by shinnlu** [rmariuzzo/Laravel-JS-Localization#168]
Hello, i always developing with Brave browser and it working good with this package.
but i got problem on Chrome Browser
![image](https://user-images.githubusercontent.com/570246/172800397-40cdcc42-0e2d-4b62-9427-c1c02767842c.png)
Left site is Google Chrome, Right side is Brave Browser, as you can see, Google Chrome just return same string i gave.

PS: two browser are visit same url.

**Comment by shinnlu** [comment]
i just got it fixed
Laravel Lang folder should be case sensitive "zh-tw" not "zh-TW".
![image](https://user-images.githubusercontent.com/570246/172804124-0d3d1959-dedc-45d1-8b4c-8aba1d4a92b7.png)

**Comment by rmariuzzo** [comment]
Interesting, will check that out
