### ISSUE TITLE
   Exception     resources/lang doesn't exists!

### ISSUE THREAD

**Issue by fatihdurmaz** [rmariuzzo/Laravel-JS-Localization#173]
Hi, Laravel 9  use default language folder lang. but composer error    
Exception /Users/fatihdurmaz/Sites/yuumawebapp/**resources/lang** doesn't exists!

**Comment by fatihdurmaz** [comment]
I solved: 
LaravelJsLocalizationServiceProvider -> Line 75 edit /resources/lang to /lang

**Comment by Ycfx** [comment]
@fatihdurmaz Or you can just move your lang folder to the resources folder, since both are accepted on Laravel 9

**Comment by dib258** [comment]
Or use the command with the specific argument to choose the source folder.
Like this -> `php artisan lang:js -s lang`
