### ISSUE TITLE
Uncaught TypeError: Lang.get is not a function in Reactjs-Laravel

### ISSUE THREAD

**Issue by MohammadAbdorrahmani** [rmariuzzo/Laravel-JS-Localization#177]
I did all the mentioned steps, but it gives me an error
in React: I am `import Lang from "lang.js";` and `<p>{Lang.get('messages.home')}</p>`
and error: `Uncaught TypeError: Lang.get is not a function`
Can anyone guide me?

Thanks

**Comment by rmariuzzo** [comment]
@MohammadAbdorrahmani before using an instance method, you have to create an instance from `Lang` see this example: https://github.com/rmariuzzo/Lang.js/#get
