### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by EmilMoe** [rmariuzzo/Laravel-JS-Localization#178]
Laravel 10 was released today and this library needs to be updated

**Comment by rmariuzzo** [comment]
I will do my best to check that during the following 2 weeks.

**Comment by EmilMoe** [comment]
> I will do my best to check that soon.

I did a fork till you have had time, only changing dependencies to allow `^10.0`. So far I haven't faced any issues.

**Comment by rmariuzzo** [comment]
If you haven't, can you create a PR?

**Comment by EmilMoe** [comment]
But I can't say if it has impacts I don't know about as my tests are only based on running `php artisan lang:js`

https://github.com/rmariuzzo/Laravel-JS-Localization/pull/179

**Comment by rmariuzzo** [comment]
New version published: https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.10.0
