### ISSUE TITLE
Call to undefined method: LangJsGenerator::make() 

### ISSUE THREAD

**Issue by okaufmann** [rmariuzzo/Laravel-JS-Localization#19]
When I try to run ```php artisan lang:js``` I get the Error in the title.

**Solution:**
The right name of the Method is ```generate()``` not ```make()```
https://github.com/rmariuzzo/Laravel-JS-Localization/blob/master/src/Mariuzzo/LaravelJsLocalization/Generators/LangJsGenerator.php#L41

Accept my Merge Request to fix this.

**Comment by rmariuzzo** [comment]
Hey @okaufmann! Thanks for spotting this. I will fix it right away!

**Comment by rmariuzzo** [comment]
Fixed!

**Comment by okaufmann** [comment]
Hey, you welcome ;) Thanks for your package!
