### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by dariocarbone** [rmariuzzo/Laravel-JS-Localization#194]
Please, could you update dependencies for Laravel 11?
Thanks

**Comment by Jaun2** [comment]
@rmariuzzo Do you have any update on when we can expect the new relaease with Laravel 11 support?

**Comment by dariocarbone** [comment]
Any news? Could you please ell us how long to wait before a new official release? I've noticed you already updated the master branch..

**Comment by rmariuzzo** [comment]
Working on this now: https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.11.1
Released: https://packagist.org/packages/mariuzzo/laravel-js-localization#v1.11.1

Once again, I apologize for the long response on this.
