### ISSUE TITLE
Separate JS library from Laravel Package

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Laravel-JS-Localization#20]
To simplify the development of this package, I have been thinking on separating the JS library from this Laravel Package. In the end we will have:

 - **rmariuzzo/laravel-js-localization** — The Laravel package.
 - **rmariuzzo/lang-js** — The JS lang library.

What do you think collaborators? @gpopoteur @xAockd @okaufmann

**Comment by gpopoteur** [comment]
@rmariuzzo it does makes sense, as lang-js has its own API for interacting with the generated lang files

**Comment by rmariuzzo** [comment]
Thanks for your opinion @gpopoteur on this. Definitively, it makes sense to me to have it separated. As you said the JS library has its own API, and also, it can live without the package ;)

As for the Laravel Package, I will include the library as a `git submodule`.

**Comment by xAockd** [comment]
It's a good idea, but will be great if the package will have some basic js file, with general functionality. And some mechanism to replace it without any problem. Because in most cases the package covers almost all requirements.

**Comment by okaufmann** [comment]
I'm with you all as well based on the given arguments!

Seperation would be cool ;)

**Comment by rmariuzzo** [comment]
The day has come when the separation was realised: https://github.com/rmariuzzo/Lang.js
