### ISSUE TITLE
Move package to "rmariuzzo" instead of "mariuzzo".

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Laravel-JS-Localization#21]
There's one char differences between the repo in GH and the package published in Packagist:

```php
rmariuzzo/Laravel-JS-Localization # Github
•mariuzzo/Laravel-JS-Localization # Packagist
```

In the past this lead me to confusion when installing the package via Composer, because I didn't notice the package name is without the `r` in the start.

What do you think collaborators? @gpopoteur @xAockd @okaufmann

**Comment by okaufmann** [comment]
So you accidentally have a typo in your composer package name. Do I get this correct?

**Comment by rmariuzzo** [comment]
That's the problem @okaufmann, the Composer's `composer.json` file is correct because it was published to Packagist without the `r` in the beginning, but the repo in GH have the `r`.

I'm thinking on what will be the impact on adding that `r` everywhere to make it consistent across the source code repo here in GH and the published packaged in Packagist.

**Comment by okaufmann** [comment]
From my own expirience:
If you rename your composer package requests to this will be redirected to the new one for a while.

Can anyone confirm this?

**Comment by xAockd** [comment]
Yes, I think adding *r* will be more clear and more intuitive, and protect from confusion in git\packagist

**Comment by vluzrmos** [comment]
I believe, if you change the "ownership" to that package, it will be changed/redirected on packagist.

**Comment by rmariuzzo** [comment]
I will close this issue because there's no user complaining about this. If it becomes an issue then we will reconsider it.
