### ISSUE TITLE
Tip/Idea: Use gulp to automate localization

### ISSUE THREAD

**Issue by okaufmann** [rmariuzzo/Laravel-JS-Localization#22]
I'm starting a bigger project, so I have a lot to translate.

So I thought, why could we not use gulp to publish this?

And we could: 
I used this package to extend gulp:
https://github.com/sun-zheng-an/gulp-shell

and in my gulpfile is use this:

```js
var shell = require('gulp-shell');

//......

gulp.task('langJs', shell.task('php artisan lang:js -c public/js/messages.js'));

```

Maybe it could be mentioned in documentation or is it not useful? what do you think @rmariuzzo?

**Comment by rmariuzzo** [comment]
@okaufmann Interesting the way you are using this package. I think it would be useful to mention it in the docs or in the wiki. If you are interested edit the `READMED.md` file and make a PR. :)

**Comment by vluzrmos** [comment]
That is cool. 
I used that way too, but with Elixir Task:
https://github.com/vluzrmos/lumen-slackin/blob/6e7bbcaae9457f0154dba7ff1f025388f9c08104/gulpfile.js

**Comment by okaufmann** [comment]
Okey @vluzrmos, you used the same package as I do but extended elixir instead of run it directly from gulp right?

**Comment by vluzrmos** [comment]
Yes!

**Comment by rmariuzzo** [comment]
Definitively, let's add an entry in the docs on how-to use.

**Comment by okaufmann** [comment]
@rmariuzzo you only have to accept my PR ;)

**Comment by rmariuzzo** [comment]
https://github.com/rmariuzzo/Laravel-JS-Localization/pull/23
