### ISSUE TITLE
Support Laravel 4.2

### ISSUE THREAD

**Issue by manuel-huez** [rmariuzzo/Laravel-JS-Localization#24]
It is said in the README that this library supports Laravel 4.2. However, your composer.json has a laravel dependency of laravel 5, preventing it to run on 4.2.
Is this package not compatible with 4.2 anymore, or is it a typo? I am truly interested in using it.

**Comment by vluzrmos** [comment]
That is true, all tags supports 4.1, 5.0 and now 5.1.
@rmariuzzo

**Comment by vluzrmos** [comment]
@manuel-huez you should use that version:

"mariuzzo/laravel-js-localization":"dev-master#242fc0500f633e2817e7e255f0d84b36407ffd73"

**Comment by manuel-huez** [comment]
This version produces the exact same problem

**Comment by manuel-huez** [comment]
@rmariuzzo Actually, This version isn't producing the problem, but the way of composer to handle this kind of dependency is. When specifying a specific version, composer is still loading the composer.json from the HEAD, and therefor reading the 5.* dependency. 
Would you mind updating the composer.json?

**Comment by rmariuzzo** [comment]
@manuel-huez thanks for filing an issue about this. Unfortunately, looks like I accidentally broken the support for Laravel 4.2.x with one of my latest commits trying to fix the tests.

**I would like your inputs on this. How should we deal _properly_ with multi-version support?**

I was thinking on using new versioning system that would follow Laravel Framework versions such as:

 - Laravel 4.2 :arrow_right: `rmariuzzo/laravel-js-localization#4.2.*`
 - Laravel 5.0 :arrow_right: `rmariuzzo/laravel-js-localization#5.0.*`
 - Laravel 5.1 :arrow_right: `rmariuzzo/laravel-js-localization#5.1.*`

What do you think? @manuel-huez @vluzrmos @gpopoteur @xAockd @okaufmann 

I will highly appreciate your input on this, also, let's have chat to create a “collaborator” team, have a roadmap and so on.

**Comment by vluzrmos** [comment]
I think that isn't necessary. You just need to follow the http://semver.org.

Make a branch to each "major.minor" version. The master branch would be the latest stable version, develop would be ... you know...

Mentions: @rmariuzzo @manuel-huez @gpopoteur @xAockd @okaufmann .

**Comment by manuel-huez** [comment]
Yup, creating a branch for each stable version tends to be the trend these
days.

**Comment by okaufmann** [comment]
Everything said. It's my opinion too

**Comment by luismarto** [comment]
If would be nice to provide a version that supports Laravel 4.2 even if it's a quick fix for now. As for versioning, I guess SemVer is the way to go. 
Thanks!

**Comment by manuel-huez** [comment]
Yup, it would be nice if you guys could tag the commit 242fc0500f633e2817e7e255f0d84b36407ffd73. That's really all you need to do :)

**Comment by rmariuzzo** [comment]
Cool! I will address this in a few hours.

**Comment by evilangelmd** [comment]
Any progress in this question?

**Comment by Bruno-Louvem** [comment]
Any progress in this issue? I'm needing so much of this package, but i use laravel 4.2

**Comment by rmariuzzo** [comment]
To be honest, I won’t get time until the weekend. I’m sorry to say that, but I don’t want keep saying that I will check it later. This weekend I will definitively work around and take down those issues. Thanks for sharing your interest on this.

**Comment by rmariuzzo** [comment]
Working on this right now!

**Comment by rmariuzzo** [comment]
This will be released this week under [v1.3.0](https://github.com/rmariuzzo/Laravel-JS-Localization/milestone/1).
