### ISSUE TITLE
Key messages with '-' or '_' chars

### ISSUE THREAD

**Issue by ecordani** [rmariuzzo/Laravel-JS-Localization#30]
Hi! I've noticed this strange behaviour with L5.1: if I use a key like 'foo' when I call Lang.has('messages.foo') I get true. But if I use a key like 'foo-bar' or 'foo_bar' the get method returns false.

**Comment by vluzrmos** [comment]
I can not reproduce this error.
You again generated the javascript file before you try?

What version of that package are you using?

**Comment by ecordani** [comment]
Hi, the package is the v.1.2.1. I have to investigate more on the issue
because I discovered that also random plain keys (like 'foobar') doesn't
work. I'll create a new project and try the same messages.php files.

Edoardo Cordani
Web & Mobile developer consultant
---------------------------------------------------
E-mail <edoardo.cordani@gmail.com> - Linkedin
<http://it.linkedin.com/pub/edoardo-cordani/5a/2a6/601> - Twitter
<https://twitter.com/ecordani>


2015-07-13 0:18 GMT+02:00 Vagner Luz do Carmo <notifications@github.com>:

**Comment by rmariuzzo** [comment]
@ecordani did you get the chance to replicate the issue?

**Comment by lguichard** [comment]
@rmariuzzo I have same problem with key message index.

For example if i use message.foo_bar method return correct string. But with message.foo.bar method return false

**Comment by rmariuzzo** [comment]
@lguichard I will take a look on this in a few hours. Thanks for expanding on this issue, [we appreciate](https://github.com/rmariuzzo/Laravel-JS-Localization/graphs/contributors) that.

**Comment by lguichard** [comment]
@rmariuzzo np ;-)

**Comment by lguichard** [comment]
@rmariuzzo Did you find a solution ?

**Comment by rmariuzzo** [comment]
Sorry for the long delay, I have been pretty busy, doctor appointments and relocating. Will create some time this week. Feel free to ping me.
Rubens Mariuzzo
rubens@mariuzzo.com

**Comment by ecordani** [comment]
Hi Rubens!
I've updated Laravel to the latest version in my project and now all the translations work as expected.
