### ISSUE TITLE
RU localization and Symfony localization

### ISSUE THREAD

**Issue by autaut03** [rmariuzzo/Laravel-JS-Localization#33]
In laravel I'm using Symfony localization, like this:
"{0}Items|{1}Item|[2,Inf]Items" etc
But your addon doesnt support it. Could u please add support of such things?

**Comment by a-komarev** [comment]
@autaut03 This is not this package responsibility. This package only converting Laravel's php files in javascript. But it has [Lang.js library](https://github.com/rmariuzzo/Lang.js) attached as submodule and doing the job you need.

Right now it's working only with couple languages, but I've made [PR in Lang.js to handle pluralization](https://github.com/rmariuzzo/Lang.js/pull/27).

**Comment by a-komarev** [comment]
I'm closing this issue because PR is merged already.

**Comment by rmariuzzo** [comment]
Thank you
