### ISSUE TITLE
[Idea]Select which lang files to target

### ISSUE THREAD

**Issue by JapSeyz** [rmariuzzo/Laravel-JS-Localization#36]
Hey.

I am only gonna be using a few lang files in my project, so converting them all to JS seems like a bit of an overkill.

It'd be much nicer if I could do something like resources/lang/(All where name == x) etc.

That way I could collect all my langs for JS in a single file.

**Comment by rmariuzzo** [comment]
Hey @JapSeyz! Thanks for sharing such interesting idea. I agree that if we have hundredth of language lines and we just need a few, it doesn't make sense to convert them all. What could the CLI syntax for this?

**Comment by JapSeyz** [comment]
Yeah, that'd be perfect.

Will this also take all locales?

**Comment by rmariuzzo** [comment]
Should be useful to filter locales? I don't think so, but I'm open to listen different opinion on this matter.

**Comment by JapSeyz** [comment]
I didn't mean filter. I just don't know if it only takes the primary locale, or it takes them all and turns them into JS?

**Comment by rmariuzzo** [comment]
Then the answer is yes. The command process all available in languages directory.

**Comment by JapSeyz** [comment]
Ahh, fantastic!

Then my only concern is being able to select a file to process ;)

**Comment by JapSeyz** [comment]
Let me know if I can help with anything :)

**Comment by a-komarev** [comment]
Is this [feature you need](https://github.com/rmariuzzo/Laravel-JS-Localization/pull/44)?

**Comment by rmariuzzo** [comment]
Hey @JapSeyz! We just merged the ability to choose which files to be processed.
