### ISSUE TITLE
Support Laravel 5.2

### ISSUE THREAD

**Issue by sboo** [rmariuzzo/Laravel-JS-Localization#39]
Hi, 

Would you mind changing your laravel dependency to 5.1.*|5.2.*? It should work, the changes were not breaking.

Cheers,
Ramon

**Comment by micheleangioni** [comment]
Hi,
yeah, an update of Laravel version would be highly appreciated!

Thanks

**Comment by rmariuzzo** [comment]
I will work on this in a couple of mins.

**Comment by micheleangioni** [comment]
Ehi @rmariuzzo , any news about this?

**Comment by bimal72** [comment]
I really badly need this with Laravel 5.2 - as I have already production site and I wanted to update the same with Laravel 5.2

**Comment by dieg0v** [comment]
+1

**Comment by micheleangioni** [comment]
@bimal72 @dieg0v @sboo since I needed this good package for a Laravel 5.2 project of mine and PR are not to be merged, or are merged with not the pace I need, I cloned the repo and created a new project https://github.com/micheleangioni/laravel-js-lang-converter . Of course I highly credit mariuzzo for his work as main contributor of the package. PR and suggestions are welcome

**Comment by dieg0v** [comment]
hi @micheleangioni ... I think you can use the development branch on composer ... but imho fork option is best in this case, while changes are not merged in new release, you can use your fork as source. I have same problem with laravel 5.2 project and i do that on composer file:

```json
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/dieg0v/Laravel-JS-Localization",
        "reference": "mariuzzo/laravel-js-localization"
    }
],
"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.2.*",
    "mariuzzo/laravel-js-localization": "dev-master"
}
```

where my dev-master fork its same as v1.2.1 tag only with **"5.1.\*|5.2.\*"** change.

**Comment by rmariuzzo** [comment]
@micheleangioni would you like to join force and contribute to it? :smile:

**Comment by bytestream** [comment]
@rmariuzzo would you mind making a new release that includes the most recent commit supporting L 5.2?

**Comment by prYmea** [comment]
+1

**Comment by ceo-mint-soft** [comment]
+1

**Comment by mitaky** [comment]
Any updates on that issue?

**Comment by ArtbyArjan** [comment]
Running `composer require mariuzzo/laravel-js-localization`

results in:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mariuzzo/laravel-js-localization v1.2.1 requires laravel/framework 5.1.* -> no matching package found.
    - mariuzzo/laravel-js-localization v1.2.0 requires laravel/framework 5.1.* -> no matching package found.
    - Installation request for mariuzzo/laravel-js-localization ^1.2 -> satisfiable by mariuzzo/laravel-js-localization[v1.2.0, v1.2.1].
```

I'm running Laravel v 5.2.22

**Comment by hxshandle** [comment]
+1 
I use the the following in composer.json, the install works fine.
` "mariuzzo/laravel-js-localization": "dev-master"`

But when I run 
`php artisan lang:js`
I got the following error
`
  [Illuminate\Contracts\Filesystem\FileNotFoundException]
  File does not exist at path /home/vagrant/Code/gym/vendor/mariuzzo/laravel-js-localization/src/Mariuzzo/LaravelJsLocalization/Generators/../../../../Lang.js/src/lang.
  js
`

**Comment by freak3dot** [comment]
+1

**Comment by Landish** [comment]
+1

**Comment by jartaud** [comment]
composer require mariuzzo/laravel-js-localization "dev-master" --dev

**Comment by rmariuzzo** [comment]
Sorry guys for the eternal delay, [I have been sick](http://gothodgkin.tumblr.com). I will work on fixing this.

**Comment by rmariuzzo** [comment]
Any PR are more than welcome!

**Comment by jartaud** [comment]
@rmariuzzo The pain that you've been feeling, can't compare to the joy that's coming.

**Comment by Chalkin** [comment]
I'm using Laravel 5.2.43

When I do `composer require mariuzzo/laravel-js-localization` I get:

`Using version ^1.2 for mariuzzo/laravel-js-localization
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mariuzzo/laravel-js-localization v1.2.1 requires laravel/framework 5.1.* -> satisfiable by laravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - mariuzzo/laravel-js-localization v1.2.0 requires laravel/framework 5.1.* -> satisfiable by laravel/framework[5.1.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9] but these conflict with your requirements or minimum-stability.
    - Installation request for mariuzzo/laravel-js-localization ^1.2 -> satisfiable by mariuzzo/laravel-js-localization[v1.2.0, v1.2.1].`


And when i use try to use "mariuzzo/laravel-js-localization": "dev-master" like hxshandle suggested, i get the same error as he does when doing php artisan lang:js

**Comment by a-komarev** [comment]
@Chalkin Last stable version isn't support L5.2. You can can try `dev-master` if you want.

**Comment by Chalkin** [comment]
Like I wrote on the bottom, when i try dev-master I get the same error like hxshadle does.

**Comment by jartaud** [comment]
`"require-dev":` {
        "mariuzzo/laravel-js-localization": "dev-master"
 }

"scripts": {
        "post-update-cmd": [
            "cp -R resources/assets/bower/lang.js/ vendor/mariuzzo/laravel-js-localization/Lang.js/",
            "php artisan lang:js resources/assets/js/compiled/laravel.lang.js"
          ]
    },`

**Comment by rmariuzzo** [comment]
We are aiming to release version [1.3.0](https://github.com/rmariuzzo/Laravel-JS-Localization/milestone/1) this week along with this issue _finally_ fixed.
