### ISSUE TITLE
It does not work for files under folder

### ISSUE THREAD

**Issue by jaumeavila** [rmariuzzo/Laravel-JS-Localization#43]
If I want to have my translation files for the admin area under en/admin it does now work.
Let's say you have en/admin/blog.php
Then it seems it crashes.

Thanks!

**Comment by josewilsoncc** [comment]
+1 (y) It does not work for files under folder

**Comment by a-komarev** [comment]
I have language file: `lang/en/forum/thread.php`

Right now generator is making an object:

```js
{
    "en.forum.thread": {
        'allThreads': 'Show all threads'
    }
}
```

So we should implement object nesting for directories in generator and an issue will be solved.

```js
{
    "en.forum": {
        "thread": {
            'allThreads': 'Show all threads'
        },
    }
}
```

**Comment by a-komarev** [comment]
My bad. Laravel is working not as expected, API then should be: `get('forum/thread.allThreads')` and that will be easier to implement on javascript side.

**Comment by a-komarev** [comment]
Another solution is generate messages like:

```js
{
    "en.forum/thread": {
        'allThreads': 'Show all threads'
    }
}
```
