### ISSUE TITLE
Feature: Default location of generated JS file

### ISSUE THREAD

**Issue by michalkozikcombc** [rmariuzzo/Laravel-JS-Localization#59]
Maybe there should be some option to define default location of messages.js file?
For example if someone want to have it in `public/js/messages.js`, he has to provide every time this localization in `php artisan lang:js`

**Comment by rmariuzzo** [comment]
I think this a good idea. I consider the configuration file to be the right
place or that. What do you think?

**Comment by rmariuzzo** [comment]
@michalkozikcombc  just a heads up! As this is not a bug but more a feature, I will work toward releasing it this week.

**Comment by rtheunissen** [comment]
This would be very handy. Would this be as simple as a configuration for `path` as part of the config?

**Comment by a-komarev** [comment]
I like the idea but i think that `output_path` or `output_file` would be more explicit and intuitive.

**Comment by rtheunissen** [comment]
Can we get this released please? ✨

**Comment by rmariuzzo** [comment]
I will check that tomorrow and let you know.

**Comment by a-komarev** [comment]
@rmariuzzo ping :}
