### ISSUE TITLE
Take current locale from html "lang" attribute

### ISSUE THREAD

**Issue by edgarsn** [rmariuzzo/Laravel-JS-Localization#60]
It would be cool, if JS plugin would take current locale from HTML "lang" attribute. And if developer needs, he can call Lang.setLocale to override.

**Comment by a-komarev** [comment]
@edgarsn interesting proposal. @rmariuzzo what do you think about it?

PRs are welcomed :}

**Comment by rmariuzzo** [comment]
I think this could be fine if we will always aim the browser. Otherwise, if the generated library is used in other environment, I think this feature will be a little too env-specific.

Also, I understand that's very simple to make this in one line.

```js
Lang.setLocale(document.documentElement.lang)
```

I will keep this issue open so we can discuss it and see what could be done.

**Comment by mendrinos** [comment]
+1 from my side for this.

Main reason, I don't want to have on my header: 

`<script type="text/javascript">
	Lang.setLocale('{{App::getLocale()}}');
</script>`

I think everyone nowadays is having the locale defined on the html tag:

`<html lang="{{App::getLocale()}}">`

So why not to pick it up directly from there? and indeed if the user needs to override it then he should be able to..

Looking forward!

**Comment by rmariuzzo** [comment]
I agree this should be added as a feature. @mendrinos can you create an issue directly to the JS library repo instead? 

**[New Issue @ Lang.js](https://github.com/rmariuzzo/Lang.js/issues/new)**

---

I will keep this issue open to track when this feature is available in both the JS and Laravel libs.

**Comment by rmariuzzo** [comment]
Good news! This was released recently: https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.3.3
