### ISSUE TITLE
Lang.choice not working correctly

### ISSUE THREAD

**Issue by zgabievi** [rmariuzzo/Laravel-JS-Localization#64]
`en/site.php`
```php
'views_count' => '{0} No Views|{1} :count View|[2,Inf] :count Views'
```

`JS Console`
```js
Lang.choice('site.views_count', 0, {'count': 0})
```

**Output:** "0 View"

```js
Lang.choice('site.views_count', 1, {'count': 1})
```

**Output:** "No Views"

```js
Lang.choice('site.views_count', 2, {'count': 2})
```

**Output:** "2 View"

**Comment by rmariuzzo** [comment]
I have reproduced this issue successfully with the info you provided @zgabievi. I'm working on a fix to be hot released.

**Comment by rmariuzzo** [comment]
I have released a hot fix on rmariuzzo/Lang.js repository: https://github.com/rmariuzzo/Lang.js/releases/tag/v1.1.4

I will update this one shortly.

**Comment by rmariuzzo** [comment]
Released: https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.3.3

Happy coding @zgabievi !

**Comment by zgabievi** [comment]
Nice work! 👌 Thanks
