### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by olelis** [rmariuzzo/Laravel-JS-Localization#65]
Hello, there are small bug in the code.

Problem is that on windows directory separator is "\" instead of "/".

That means, that following code you have won't work:

\Mariuzzo\LaravelJsLocalization\Generators\LangJsGenerator::isMessagesExcluded

```
protected function isMessagesExcluded($filePath)
    {
        if (empty($this->messagesIncluded)) {
            return false;
        }

        $localeDirSeparatorPosition = strpos($filePath, '/');
        $filePath = substr($filePath, $localeDirSeparatorPosition);
        $filePath = ltrim($filePath, '/');
        $filePath = substr($filePath, 0, -4);

        if (in_array($filePath, $this->messagesIncluded)) {
            return false;
        }

        return true;
    }
```

Please, fix it so it will work on windows too.

Easy fix would be to add following replace:
`$filePath = str_replace(DIRECTORY_SEPARATOR,'/',$filePath);`

However, I am not sure that this will be sufficient.

Please, take a look on this, I can test on windows, if needed.

**Comment by rmariuzzo** [comment]
Perfect, I will check on it this weekend. I'm in the hospital right now for
a scheduled chemo.

**Comment by a-komarev** [comment]
@rmariuzzo I will check the code ASAP. That's my fault :}

**Comment by a-komarev** [comment]
Solution is published, but I don't have any Windows machines to test it. Help required :sos:

**Comment by oliski** [comment]
I cqn check ok monday

**Comment by olelis** [comment]
Nope, does not work.

Here is the link to my pull request: https://github.com/rmariuzzo/Laravel-JS-Localization/pull/67

**Comment by rmariuzzo** [comment]
I'm configuring a Windows image to test this and release if it looks good.

**Comment by rmariuzzo** [comment]
I'm still working on it. It is a pain to setup the env in Windows... 😞

**Comment by rmariuzzo** [comment]
I partially run the test on Windows, because there were a bunch of edge cases that are like rabbit holes that goes deeper and deeper. Not directly related to this lib, but because of the dependencies on Windows.

**Comment by rmariuzzo** [comment]
Released: https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.3.4
