### ISSUE TITLE
Update Lang.js submodule reference

### ISSUE THREAD

**Issue by werdlv** [rmariuzzo/Laravel-JS-Localization#68]
Issue [#39](https://github.com/rmariuzzo/Lang.js/issues/39) on [Lang.js](https://github.com/rmariuzzo/Lang.js) was fixed and therefore this repo's submodule reference should be updated as well to fix the issue for this library users.

**Comment by rmariuzzo** [comment]
Working on this.

**Comment by rmariuzzo** [comment]
Fixed and released! https://github.com/rmariuzzo/Laravel-JS-Localization/releases/tag/v1.3.5
