### ISSUE TITLE
artisan command not working

### ISSUE THREAD

**Issue by kwiqadmin** [rmariuzzo/Laravel-JS-Localization#69]
I have installed it on a laravel project. But I don’t get the artisan command to work. I always get:  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "lang" namespace.

**Comment by rmariuzzo** [comment]
Hey @kwiqadmin!

Thanks for your time on file an issue. What is the command you are typing?

**Comment by kwiqadmin** [comment]
I already found the solution:
I had to do:
`php artisan config:clear`

now php artisan lang:js works again. Thanks anyway :)

**Comment by rmariuzzo** [comment]
Cool! Happy coding @kwiqadmin !

**Comment by Richard2012** [comment]
Same here. Problem with artisan lang
` php artisan lang:publish`
returns
` ERROR  There are no commands defined in the "lang" namespace.`
All other artisan commands work fine. This is on Laravel 9.

**Comment by sbaum2s** [comment]
> Same here. Problem with artisan lang ` php artisan lang:publish` returns ` ERROR There are no commands defined in the "lang" namespace.` All other artisan commands work fine. This is on Laravel 9.

It works on Laravel 10. Need to upgrade project from Laravel 9.
