### ISSUE TITLE
Feature: Ability to specify path in configuration file

### ISSUE THREAD

**Issue by KwiqAndre** [rmariuzzo/Laravel-JS-Localization#70]
Sometime the language files can get very big. I usually create language files for each page. To avoid that all other language strings (from other pages) get loaded it would be cool, if I could specify via elixir by parameter which language files should be pulled, so that i can create a language js file for each page. The loading overhead can be reduced that way.

**Comment by a-komarev** [comment]
#49 Is this what you need? Or you want to dynamically load translations files on page loading?

**Comment by KwiqAndre** [comment]
Yes, thats what I need, only with include.

**Comment by rmariuzzo** [comment]
All good then @KwiqAndre ?

**Comment by kwiqadmin** [comment]
this is not in your current version, or am I wrong?
I have to fork it?

**Comment by a-komarev** [comment]
@kwiqadmin it's in current version. See #47  #48

**Comment by kwiqadmin** [comment]
artisan lang:js -e auth

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "-e" option does not exist.

**Comment by a-komarev** [comment]
Manual exclusion is not implemented. You can define what files should be included in config file. Look for `messages` array key.

**Comment by kwiqadmin** [comment]
I know that. but the config file is not enough. I need something, that I can create lang js files for individual pages. Right now I can have only one configuration. I want to use elixir to create several lang js files, each with another configuration.

**Comment by a-komarev** [comment]
@kwiqadmin Feel free to make a PR for the elixir which will do the job. This isn't implemented.

**Comment by KwiqAndre** [comment]
PR? I am pretty new to all that stuff (laravel, elexir ...)

**Comment by a-komarev** [comment]
@KwiqAndre Pull Request in GitHub.

What sizes of language files do you have that you decided to split them that way?

**Comment by rtheunissen** [comment]
@a-komarev the size of the file isn't really relevant here - the fact that you are loading resources that you don't need is what's important. Let's say I have 2000 messages in 20 different languages. That's a lot of string data that I would only need at most 5% of in most cases. 

A good solution for this is to not compile *all* the messages into a single javascript file. Instead, you should create a suffix for each locale, eg `lang.en.js`. That way you can use the current locale in a blade template and only source the language you need. Not sure how this works for fallbacks though.

**Comment by rtheunissen** [comment]
Actually, why not in config have a locale filter? Eg

```php
<?php

return [
    'locales' => [
        'en_us',
        'en_uk',
    ],
];

```
