### ISSUE TITLE
Bug: Unit tests doesn't run for Laravel 4.2 + <=PHP 5.6

### ISSUE THREAD

**Issue by a-komarev** [rmariuzzo/Laravel-JS-Localization#74]
At the end of unit tests you [can see](https://travis-ci.org/rmariuzzo/Laravel-JS-Localization/jobs/181049343):

```shell
OK (9 tests, 37 assertions)

> if [[ `php -v` =~ "PHP 5.6" ]]; then ./vendor/bin/phpunit --configuration tests/5.3; fi
sh: 1: [[: not found
```

I suppose that it's `bash` syntax while CI using common `sh`.

**Comment by rmariuzzo** [comment]
Good catch @a-komarev! Didn't noticed this.

**Comment by rmariuzzo** [comment]
Hey @a-komarev! Looks there's a way to better organize our tests.

**Comment by a-komarev** [comment]
@rmariuzzo interesting features of PHPUnit, didn't knew about them.

**Comment by rmariuzzo** [comment]
I'm checking this right now and see if we can make a release with recent merges.
