### ISSUE TITLE
There are no commands defined in the "lang" namespace.

### ISSUE THREAD

**Issue by topclaudy** [rmariuzzo/Laravel-JS-Localization#75]
Running "php artisan lang:js" after installation results in "There are no commands defined in the "lang" namespace." in Laravel 5.3

**Comment by rmariuzzo** [comment]
Hey @topclaudy! Did you add this service provider: `Mariuzzo\LaravelJsLocalization\LaravelJsLocalizationServiceProvider::class` in your `app/config.php` file?

**Comment by topclaudy** [comment]
@rmariuzzo Yes I added it after installation.

**Comment by rmariuzzo** [comment]
That's weird, try running: `php artisan clear-compiled` and rerun the command. If it fails, please give details of you Laravel installation (version, os).

**Comment by topclaudy** [comment]
The issue persists after running `php artisan clear-compiled`. I'm running Laravel 5.3.26 on macOS Sierra. I also noticed that the command `php artisan vendor:publish --provider="Mariuzzo\LaravelJsLocalization\LaravelJsLocalizationServiceProvider"` doesn't publish any configuration file (Nothing to publish for tag []).

**Comment by rmariuzzo** [comment]
Hey @topclaudy! Sorry for the long delay. Did you solved this?

**Comment by tenaciousd93** [comment]
Same problem here! `Laraval 5.3` with  `mariuzzo/laravel-js-localization` v1.3.

To solve `php artisan clear-compiled` fail I ran `composer remove mariuzzo/laravel-js-localization`, and went to `bootstrap/cache/config.php` and removed the line `Mariuzzo\LaravelJsLocalization\LaravelJsLocalizationServiceProvider` in **providers** array.

Clean all with `composer clear` and `php artisan clear-compiled`.

In my other project with `Laravel 5.1` and `mariuzzo/laravel-js-localization` v1.2.* works good.

**Comment by rmariuzzo** [comment]
I will close this one for now, because I couldn't reproduce this issue. If it happens again, I will open it including more details.
