### ISSUE TITLE
The best way to display variable to html without delay by load file .js

### ISSUE THREAD

**Issue by 21110027781** [rmariuzzo/Laravel-JS-Localization#77]
Hi all,

I need print variable message to template html without delay.
Can use angularjs or javascript.

Thanks,

**Comment by a-komarev** [comment]
@21110027781 What do you mean by "without delay"?

Read [Lang.js documentation](https://github.com/rmariuzzo/Laravel-JS-Localization#documentation) to find how to get translations from javascript.

**Comment by 21110027781** [comment]
I understand. Thanks for your support :)
