### ISSUE TITLE
Feature: Optionally include JS library within generated file

### ISSUE THREAD

**Issue by ardani** [rmariuzzo/Laravel-JS-Localization#79]
Hi @rmariuzzo ,
this is great package, very usefull, i try this for my project now.
i have a problem , how to include result generate lang.js to webpack?
i try using this code but error
```
import Lang from 'lang.js';
require('./localize');
```
error message `Uncaught ReferenceError: Lang is not defined`
any solution for me?
thanks

**Comment by rmariuzzo** [comment]
If you run this:

```js
import Lang from 'lang.js';

console.log(Lang)
```

What does it print?

**Comment by ardani** [comment]
if use 
```js
import Lang from 'lang.js';
const lang = new Lang();
console.log(lang)
```
it work, but if i use import file message.js from generate `php artisan lang:js` and import it on file js error if compile using webpack show error `Lang is not defined`

**Comment by ardani** [comment]
for now i modified with add option in command `--message-only` and template `only_messages.js` like this
[#41199f8](https://github.com/ardani/Laravel-JS-Localization/commit/41199f801413ef98a93ef7f8af9f0c9d909871e2)

**Comment by rmariuzzo** [comment]
@ardani this looks great! What do you think @vluzrmos @a-komarev @gpopoteur about providing the option for generating the messages without the lib integrated? I think that proposal is pragmatic.

**Comment by a-komarev** [comment]
@rmariuzzo I think this could be useful feature.

**Comment by rmariuzzo** [comment]
@a-komarev I also share the same feeling on this. However, I would suggest to use another parameter name such as:

```shell
# Include the lang.js library (by default).
php artisan lang:js --lib

# Do not include the lang.js library.
php artisan lang:js --no-lib
```

What do you think @a-komarev ?

**Comment by a-komarev** [comment]
@rmariuzzo Good one!

**Comment by rmariuzzo** [comment]
Hey @ardani! Could you create a PR to `develop` branch with your changes + [my comments](https://github.com/rmariuzzo/Laravel-JS-Localization/issues/79#issuecomment-269694837)?

**Comment by ardani** [comment]
Ok @rmariuzzo
