### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by gerciljunio** [rmariuzzo/Laravel-JS-Localization#84]
Hello, do you have any plans to adapt to laravel 5.4? I was updating my system and found an error in [LaravelJsLocalizationServiceProvider.php](https://github.com/rmariuzzo/Laravel-JS-Localization/blob/master/src/Mariuzzo/LaravelJsLocalization/LaravelJsLocalizationServiceProvider.php) on line [67](https://github.com/rmariuzzo/Laravel-JS-Localization/blob/master/src/Mariuzzo/LaravelJsLocalization/LaravelJsLocalizationServiceProvider.php#L67), I believe that is why the share method was removed in the latest version of laravel. Thanks!

**Comment by rmariuzzo** [comment]
Hey @gerciljunio! Yes, there's a pending PR for 5.4 support, I will do my best to merge today or by tomorrow.

**Comment by joelcuevas** [comment]
How about supporting the new json files?

https://laravel.com/docs/5.4/localization#using-translation-strings-as-keys

**Comment by a-komarev** [comment]
@joelcuevas this planned for future releases.

**Comment by rmariuzzo** [comment]
@gerciljunio I have merged this: https://github.com/rmariuzzo/Laravel-JS-Localization/pull/83 which add Laravel 5.4 support. I'm now writing proper tests that match Laravel 5.4. If it all works, I'm releasing it today.

**Comment by rmariuzzo** [comment]
Quick update: I'm tracking the addition of Laravel 5.4 tests here: https://github.com/rmariuzzo/Laravel-JS-Localization/issues/86
