### ISSUE TITLE
Initialization Explanation

### ISSUE THREAD

**Issue by FFXV** [rmariuzzo/Laravel-JS-Localization#85]
Hi!

I have successfully created the messages.js file.

Now I want to use it. However, "Lang" is not recognized.
E.g., if I take from the documentation the following (not even using messages.js):

```js
var lang = new Lang({
    messages: {
        'en.greetings': {
            'hi': 'Hi'
        },
    }
});

lang.get('greetings.hi');
// > "Hi"
```

.. I cannot get any output. Actually the script stops there. I guess, I have make an import or something similar.

Thanks for any help!

**Comment by rmariuzzo** [comment]
@FFXV this could be related to https://github.com/rmariuzzo/Laravel-JS-Localization/issues/63

How are you consuming the generated JS?

**Comment by FFXV** [comment]
var lang = new Lang({
    messages: '/public/messages.js',
    locale: 'en',
});

This is in my java script. Now, the browser console says "ReferenceError: Lang is not defined".

**Comment by FFXV** [comment]
The same with the code I posted some weeks ago. Sorry, I moved.

**Comment by ameenross** [comment]
I had this problem when I passed the generated js through webpack. I changed it to bypass webpack and just output the js file to the public/ directory. I don't know what about webpack makes it break the file, but it apparently does.

**Comment by rmariuzzo** [comment]
Interesting @ameenross, we will need to see what webpack does with these files.

**Comment by rmariuzzo** [comment]
This issue will be tracked along with: #63
