### ISSUE TITLE
composer test-install?

### ISSUE THREAD

**Issue by manticorp** [rmariuzzo/Laravel-JS-Localization#88]
What is composer test-install ? and composer test? (referenced in ReadMe)

**Comment by rmariuzzo** [comment]
@manticorp 

`composer run test-install` is the command to install all dependencies to run the tests. And `composer run test` is the command to actually run the tests.

**Comment by a-komarev** [comment]
@manticorp this done because package testing not only latest supported laravel, but each previous verions.

**Comment by rmariuzzo** [comment]
Closing this since it is not an issue.

**Comment by manticorp** [comment]
Ah right I see, sorry I'm a bit embarrassed now - I didn't think to check the scripts in the composer.json file!

**Comment by rmariuzzo** [comment]
@manticorp all good mate!
