### ISSUE TITLE
Using 'Lang' class with Vue.js

### ISSUE THREAD

**Issue by adl1995** [rmariuzzo/Laravel-JS-Localization#89]
It so happens that I can't import the 'Lang' class in my Vue component; I receive a _ReferenceError_. Any help would be appreciated.

**Comment by rmariuzzo** [comment]
This is related to how the template is defined. I think this is related to another existing issue. I will check it later, since I'm in the hospital right now.

**Comment by rmariuzzo** [comment]
This one will be deal with #63

**Comment by michgeek** [comment]
My solution to that problem is to use the command **without including `Lang.js`**

1. Assuming my output is : `/resources/assets/js/messages.js`

```
// Generate the messages without the lib
php artisan lang:js --no-lib
```

```
// Install `Lang.js` as a standalone package
npm install lang.js
```

2. Create a file in `/resources/assets/js/lang.js`

```js
// Inside my /resources/assets/js/lang.js
import lang from 'lang.js';
import messages from 'js/messages';

const Lang = new lang({
    messages
});

export default Lang;
```

3. Now you can use `Lang` wherever you need

```
import Lang from `js/lang`; // ES6, with webpack configured to resolve `js => /resources/assets/js`
var Lang = require('path/to/your/lang.js'); // Alternatively

Lang.get('my.translation');
// ...
```

**Comment by josiasmontag** [comment]
Even simpler solution:

Add this filter to Vue:
```js
Vue.filter('trans', (...args) => {
    return Lang.get(...args);
});
```

Then you can do stuff like this:

```js
{{ 'messages.home' | trans }}
```
or:
```js
{{ 'messages.welcome' | trans({ name: 'Joe' }) }}
```

**Comment by a-komarev** [comment]
@josiasmontag Awesome! Thanks for the tip!

**Comment by sistemaswebbrasil** [comment]
Testing just like michgeek showed I get to catch the message object with `console.log (Lang)`, but if I try to get some text with `Lang.get ('messages.hello')`, the chrome console returns me: Uncaught TypeError : Lang.get is not a function

**Comment by PhPPgAdminBug** [comment]
`window.Lang= require('lang.js');

alert(window.Lang);`

returns 
`function(options){
        options = options || {};
        this.locale = options.locale || inferLocale() || defaults.locale;
        this.fallback = options.fallback;
        this.messages = options.messag…
}`

But functions are not avaiable.
alert(window.Lang);`

Returns 
`Uncaught TypeError : Lang.get is not a function`

same as above.

**Comment by rmariuzzo** [comment]
Hi @PhPPgAdminBug! Try creating an instance:

```js
var lang = new window.Lang;
alert(lang.get('my.trans_word');
```

**Comment by PhPPgAdminBug** [comment]
@rmariuzzo `Uncaught TypeError: window.Lang is not a constructor`

**Comment by PhPPgAdminBug** [comment]
Figured that 
`
window.Lang = require('lang.js/src/lang');
console.log(window.Lang = new Lang({
    messages: document.location.hostname + '/js/messages.js',
}));
`

returns 
`Lang {locale: "ru", fallback: undefined, messages: "domain.app/js/messages.js"}`

But:
`window.Lang = require('lang.js/src/lang');
console.log(window.Lang = new Lang({
    messages: document.location.hostname + '/js/messages.js',
}).has('somte.word'));`

is always **FALSE**, while messages path to file is right, and there are all messages

**Comment by rmariuzzo** [comment]
@PhPPgAdminBug the `messages` value should not be a path, instead it should the messages.js file contents. Please, double check that.

**Comment by rmariuzzo** [comment]
The original reported issue will be tracked at: #63
