### ISSUE TITLE
Problems for laravel 4

### ISSUE THREAD

**Issue by evilangelmd** [rmariuzzo/Laravel-JS-Localization#90]
Hello. i have some problems when i updated package. I use laravel 4, and when i tried to generate javascript.js file, using:
`php artisan lang:js`
i had an error: 

>   [Exception]
> /Users/apple/Documents/project/laravel/resources/lang doesn't exists!

I am not sure, but maybe this depends on line 69 of LaravelJsLocalizationServiceProvider.php file...

**Comment by rmariuzzo** [comment]
Hey @evilangelmd!

I will ask something simple, does this path `/Users/apple/Documents/project/laravel/resources/lang` exist?

**Comment by evilangelmd** [comment]
no, on L4 the path is: /Users/apple/Documents/project/laravel/app/lang
on L5 path was changed to resources/lang but in L4 was app/lang
![screen shot 2017-03-06 at 10 15 09](https://cloud.githubusercontent.com/assets/6436504/23603520/e0ca84d0-0255-11e7-8208-fbf0dc5677c2.png)

**Comment by evilangelmd** [comment]
infact this bug was even in 1.2.0 that i use till last week, but when i used for first time, i had deadlines near, so i maked a fork and made it compatible with L4 exclusively, After that project i forgot it till last week when project manager wanted to update L4.

**Comment by evilangelmd** [comment]
And another think, it is possible to do for L4 min php version >=5.4.0 ?

**Comment by aimakun** [comment]
@rmariuzzo Hello, I'm not sure what we need to do about this issue. It's updating composer.json to PHP 5.4+, isn't it?

**Comment by rmariuzzo** [comment]
@aimakun we need to check at Laravel site what is the minimum PHP requirement for Laravel 4.2 and then see if we need to change something.

**Comment by aimakun** [comment]
I'm actively working on project that still using Laravel 4.2 and it appeared in composer.lock that require PHP 5.3+. I think just update to same version (>=5.3.0) should works fine.

But for Laravel 5+ it would require PHP 5.5+. Should it be separate tags specific for Laravel 4?

**Comment by aimakun** [comment]
FYI, Laravel 5.5 and up now require PHP >= 7.0 as described here: https://laravel.com/docs/5.5/installation

**Comment by rmariuzzo** [comment]
We currently use the same branch/tag for both 4/5 major version. Then we
will need to update our composer.json.

**Comment by aimakun** [comment]
Ah, I forgot that Composer would resolve PHP version based on all dependencies. I think no problem for update project's composer.json anyway. If Laravel or other dependencies required higher PHP version, Composer should update by itself.
