### ISSUE TITLE
Laravel 5.4 Pluralization Standard

### ISSUE THREAD

**Issue by wapacro** [rmariuzzo/Laravel-JS-Localization#99]
Laravel 5.4 introduces the asterisk symbol for defining the infinity of a pluralization string (instead of «Inf») which gets ignored by Lang.js using the Artisan command to generate the lang.js file.

See https://laravel.com/docs/5.4/localization#pluralization

**Comment by rmariuzzo** [comment]
@wapacro thank you for reporting this issue, can you add it on https://github.com/rmariuzzo/Lang.js to follow this issue from the right repo? Thank you 👍
